version: "3.5"
services:
  app:
    container_name: tigeratacado-default
    image: tigeratacado
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/var/www/html
    environment:
      - XDEBUG_START_WITH_REQUEST=yes
      - XDEBUG_DISCOVER_CLIENT_HOST=false
    ports:
      - "${DOCKER_APP_PORT}:80"
    networks:
      - tigeratacado
  redis:
    container_name: container-redis
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
    image: redis:4.0-alpine
    ports:
      - "${DOCKER_REDIS_PORT}:6379"
    networks:
      - tigeratacado
    volumes:
      - ./.docker/data/redis:/data
    depends_on:
      - app

networks:
  tigeratacado:
    name: tigeratacado
    driver: bridge
